name: kulshe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_unicons: 0.0.1
  shared_preferences: ^0.5.12+4
  url_launcher: ^6.0.3
  whatsapp_unilink: ^2.0.0
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  toast: ^0.1.5
  splashscreen: ^1.3.5
  country_list_pick: ^1.0.1+3
  flutter_svg: ^0.19.1
  rflutter_alert: ^1.0.3
  connectivity: ^3.0.2
#  provider: ^4.3.3
  image_picker: ^0.6.7+12
  email_validator: ^2.0.1
  list_tile_switch: ^1.0.0
  #  devicelocale: ^0.4.1
  #  country_codes: ^1.0.3
  animated_dialog_box: ^0.0.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.9
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^9.0.0
  page_view_indicator: ^2.0.4
  intl: ^0.16.1
#  multi_image_picker: ^4.6.9
  multi_image_picker2: ^5.0.0
  flutter_absolute_path: ^1.0.6
#  simple_location_picker: ^0.0.3
#  nominatim_location_picker: ^0.1.0+7
#  google_maps_place_picker: ^1.0.0
  map_pin_picker: ^0.0.1
  google_maps_flutter: ^1.1.1
  geocoder: ^0.2.1
  video_player: ^0.10.1
  provider: ^5.0.0
  share: ^2.0.1
  flutter_html: ^0.11.0
  carousel_slider:
  bmprogresshud: ^0.0.10

  badges: ^1.2.0
  youtube_player_flutter: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
